# Generated by Django 2.1.2 on 2018-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallarymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShelterCode', models.IntegerField()),
                ('Organization', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('UserName', models.CharField(max_length=255)),
                ('MajorTasks', models.CharField(max_length=255)),
                ('Tasks', models.CharField(max_length=255)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('SubDate', models.DateField()),
                ('Comments', models.CharField(max_length=1000)),
                ('Image1', models.CharField(max_length=255)),
                ('Image1Caption', models.CharField(max_length=255)),
                ('Image2', models.CharField(max_length=255)),
                ('Image2Caption', models.CharField(max_length=255)),
                ('Image3', models.CharField(max_length=255)),
                ('Image3Caption', models.CharField(max_length=255)),
                ('Image4', models.CharField(max_length=255)),
                ('Image4Caption', models.CharField(max_length=255)),
                ('Image5', models.CharField(max_length=255)),
                ('Image5Caption', models.CharField(max_length=255)),
            ],
        ),
    ]
