# Generated by Django 2.1.2 on 2018-10-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0002_auto_20181025_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='SubDate',
            field=models.CharField(max_length=255),
        ),
    ]
