# Generated by Django 2.1.2 on 2018-10-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0003_auto_20181025_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='SubDate',
            field=models.DateField(),
        ),
    ]
