# Generated by Django 2.1.2 on 2018-10-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0004_auto_20181025_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymodel',
            name='SubDate',
        ),
    ]
