# Generated by Django 2.1.2 on 2018-10-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0005_remove_gallerymodel_subdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='ShelterCode',
            field=models.CharField(max_length=255),
        ),
    ]
